ita-social-projects/EPlast

- EPlast/EPlast.DataAccess/Repositories/Interfaces/Base/IRepositoryBase.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Base/RepositoryBase.cs
Created async methods for repositories:
- get all
- get first
- get first or default
- get last
- get last or default
- get single
- get single or default
> Async repositories

- EPlast/EPlast.BussinessLayer/Interfaces/City/ICItyAdministrationService.cs
- EPlast/EPlast.BussinessLayer/Interfaces/City/ICityService.cs
- EPlast/EPlast.BussinessLayer/Services/City/CityAdministrationService.cs
- EPlast/EPlast.BussinessLayer/Services/City/CityMembersService.cs
- EPlast/EPlast.BussinessLayer/Services/City/CityService.cs
- EPlast/EPlast.XUnitTest/Controllers/AnnualReportControllerTests.cs
- EPlast/EPlast.XUnitTest/Controllers/CityControllerTests.cs
- EPlast/EPlast.XUnitTest/Services/City/CityAdministrationServiceTests.cs
- EPlast/EPlast.XUnitTest/Services/City/CityMembersServiceTests.cs
- EPlast/EPlast.XUnitTest/Services/City/CityServiceTests.cs
- EPlast/EPlast/Controllers/AnnualReportController.cs
- EPlast/EPlast/Controllers/CItyController.cs
Implemented async repositories into city services.
Added unit tests for city administration and city members services.
Fixed code smell in city services
> Code refactoring

- EPlast/EPlast.BLL/DTO/AnnualReport/AnnualReportDTO.cs
- EPlast/EPlast.BLL/Interfaces/AnnualReport/IAnnualReportService.cs
- EPlast/EPlast.BLL/Services/AnnualReport/AnnualReportService.cs
- EPlast/EPlast.DataAccess/Entities/AnnualReport/AnnualReport.cs
- EPlast/EPlast.DataAccess/Migrations/20200720095814_Remove_NumberOfSeatsCity_AnnualReport_table.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20200720095814_Remove_NumberOfSeatsCity_AnnualReport_table.cs
- EPlast/EPlast.Resources/AnnualReportControllerMessage.cs
- EPlast/EPlast.Resources/AnnualReportControllerMessage.uk.resx
- EPlast/EPlast.Resources/EPlast.Resources.csproj
- EPlast/EPlast.WebApi/Controllers/AnnualReportController.cs
- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
- EPlast/EPlast.XUnitTest/Controllers/AnnualReportControllerTests.cs
- EPlast/EPlast.XUnitTest/Services/AnnualReport/AnnualReportServiceTests.cs
- EPlast/EPlast/Controllers/AnnualReportController.cs
Created resources file for annual report api controller
Changed logger messages for annual report api controller
Created method to get annual report statuses
Created method to get city legal statuses
Removed NumberOfSeatsCity field from AnnualReport table
> Ab annual report

- EPlast/EPlast.BLL/Interfaces/AnnualReport/IAnnualReportService.cs
- EPlast/EPlast.BLL/Services/AnnualReport/AnnualReportService.cs
- EPlast/EPlast.Resources/AnnualReportControllerMessage.uk.resx
- EPlast/EPlast.WebApi/Controllers/AnnualReportController.cs
- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
- EPlast/EPlast.XUnitTest/Services/AnnualReport/AnnualReportServiceTests.cs
> Annual report

- EPlast/EPlast.BLL/Interfaces/Admin/IAdminService.cs
- EPlast/EPlast.BLL/Interfaces/AzureStorage/Base/IAzureBlobConnectionFactory.cs
- EPlast/EPlast.BLL/Interfaces/AzureStorage/Base/IBlobStorageRepository.cs
- EPlast/EPlast.BLL/Interfaces/UserProfiles/IDegreeService.cs
- EPlast/EPlast.BLL/Interfaces/UserProfiles/IEducationService.cs
- EPlast/EPlast.BLL/Interfaces/UserProfiles/IGenderService.cs
- EPlast/EPlast.BLL/Interfaces/UserProfiles/INationalityService.cs
- EPlast/EPlast.BLL/Interfaces/UserProfiles/IReligionService.cs
- EPlast/EPlast.BLL/Interfaces/UserProfiles/IUserService.cs
- EPlast/EPlast.BLL/Interfaces/UserProfiles/IWorkService.cs
- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
- EPlast/EPlast.BLL/Services/AzureStorage/Base/AzureBlobConnectionFactory.cs
- EPlast/EPlast.BLL/Services/AzureStorage/Base/BlobStorageRepository.cs
- EPlast/EPlast.BLL/Services/UserProfiles/DegreeService.cs
- EPlast/EPlast.BLL/Services/UserProfiles/EducationService.cs
- EPlast/EPlast.BLL/Services/UserProfiles/GenderService.cs
- EPlast/EPlast.BLL/Services/UserProfiles/NationalityService.cs
- EPlast/EPlast.BLL/Services/UserProfiles/ReligionService.cs
- EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
- EPlast/EPlast.BLL/Services/UserProfiles/WorkService.cs
- EPlast/EPlast.WebApi/Controllers/AdminController.cs
- EPlast/EPlast.WebApi/Controllers/UserController.cs
- EPlast/EPlast.WebApi/Startup.cs
- EPlast/EPlast.WebApi/appsettings.json
Add documentation to UserController, UserService, User profile services, Azure services;
Add create roles to startup;
> Vv user documentation

- EPlast/EPlast.BLL/Interfaces/AnnualReport/IAnnualReportService.cs
- EPlast/EPlast.BLL/Services/AnnualReport/AnnualReportService.cs
- EPlast/EPlast.WebApi/Controllers/AnnualReportController.cs
- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
Created documentation for annual report controller
Created documentation for annual report service
Created method (cities controller) to get all cities that the user has access to
> Documentation

- EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
#186  Added unit tests for all methods in UserController
> Task#186 Added Unit tests for UserConroller

- EPlast/EPlast.Tests/Controllers/EventsControllerTests.cs
#185 Added unit tests for some methods in EventsController (That are methоds for Event Gallery)
Changed some access modifiers.
> Added unit tests for some methods in EventsController

- EPlast/EPlast.Tests/Controllers/DecisionsControllerTests.cs
- EPlast/EPlast.Tests/Controllers/EventCalendarControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
Added UnitTests for EventCallendarController, DecisionsController, refactored ClubController.  #187 #188
> UnitTests EventCallendarController, DecisionsController. Refactroring ClubController

- EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
- EPlast/EPlast.Tests/Controllers/AnnualReportControllerTests.cs
- EPlast/EPlast.Tests/Controllers/CityControllerTests.cs
Deleted commented code, fixed code smells
> Unit tests

- EPlast/EPlast.BLL/Services/City/CityAccess/CityAccessGetters/CityAccessForCityAdminGetter.cs
> Id fixes before demo

- EPlast/EPlast.Tests/Controllers/ClubControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
> Added UnitTests for ClubController

- EPlast/EPlast.DataAccess/Entities/City/CityAdministration.cs
- EPlast/EPlast.DataAccess/Entities/City/CityLegalStatus.cs
- EPlast/EPlast.DataAccess/Migrations/20200810114849_Set_OneToMany_CityLegalStatus_CityManagement.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20200810114849_Set_OneToMany_CityLegalStatus_CityManagement.cs
- EPlast/EPlast.DataAccess/Migrations/20200810115324_Set_OneToMany_CityAdministration_CityManagement.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20200810115324_Set_OneToMany_CityAdministration_CityManagement.cs
Set one-to-many relation between CityLegalStatus and CityManagement
Set one-to-many relation between CityAdministration and CityManagement
> Fix database

- EPlast/EPlast.BLL/Services/UrlOptions/UrlOptions.cs
- EPlast/EPlast.Tests/Controllers/AuthControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/AuthController.cs
- EPlast/EPlast.WebApi/Startup.cs
- EPlast/EPlast.WebApi/appsettings.json
- EPlast/EPlast.XUnitTest/Controllers/AccountControllerTests.cs
Reverts ita-social-projects/EPlast#385
> Revert "Changed url"

- EPlast/EPlast.BLL/Services/City/CityService.cs
> Fixed deleting

- azure-pipelines.yml
- manifests/cert-issuer-prod.yml
- manifests/cert-prod.yml
- manifests/deployment.yml
- manifests/ingress-prod.yml
- manifests/redis-master-deployment.yaml
- manifests/redis-master-service.yaml
- manifests/service.yml
Updated manifests and azure pipeline
> Update azure pipeline for kuber

- azure-pipelines.yml
> Update azure pipeline

- EPlast/EPlast.BLL/DTO/AnnualReport/MembersStatisticDTO.cs
- EPlast/EPlast.BLL/Interfaces/Statistics/ICityStatisticsService.cs
- EPlast/EPlast.BLL/Interfaces/Statistics/IRegionStatisticsService.cs
- EPlast/EPlast.BLL/Services/Statistics/StatisticsService.cs
Changed Statistics interfaces
Rafactoring
Resolved problem with MembersStatisticsDTO
> Added one new service

- EPlast/EPlast.BLL/Interfaces/EventUser/IEventUserManager.cs
- EPlast/EPlast.BLL/Services/EventUser/EventUserManager.cs
- EPlast/EPlast.BLL/Services/Events/EventCategoryManager.cs
- EPlast/EPlast.WebApi/Controllers/EventsUsersController.cs
Added opportunity to approve events by eventAdmin
> Approved events

- EPlast/EPlast.BLL/Services/Region/RegionAdministrationService.cs
> Fix region secretary

- EPlast/EPlast.BLL/Interfaces/Club/IClubAnnualReportService.cs
- EPlast/EPlast.BLL/Services/Club/ClubAnnualReportService.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
> Added possibility to edit, cancel and delete clubAnnualReport

- EPlast/EPlast.BLL/Services/Club/ClubService.cs
> Fix for club members and admins

- EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
- EPlast/EPlast.Tests/Services/Regions/RegionAdministrationServiceTests.cs
- EPlast/EPlast.Tests/Services/Regions/RegionAnnualReportServiceTest.cs
- EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> Regions tests

- EPlast/EPlast.Tests/Services/City/CityAdministrationServiceTests.cs
- EPlast/EPlast.Tests/Services/City/CityServiceTests.cs
> Added unit-tests for CityService, CityAdminService

- EPlast/EPlast.BLL/Services/Club/ClubService.cs
- EPlast/EPlast.BLL/Services/Region/RegionService.cs
- EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
> Added check for already created regions and clubs

- EPlast/EPlast.Tests/Services/Event/EventAdministrationManagerTests.cs
- EPlast/EPlast.Tests/Services/Event/EventCalendarServiceTests.cs
- EPlast/EPlast.Tests/Services/Event/EventsManagerTests.cs
- EPlast/EPlast.Tests/Services/Regions/RegionAccessForAdminGetterTests.cs
- EPlast/EPlast.Tests/Services/Regions/RegionAccessForRegionAdminGetterTests.cs
- EPlast/EPlast.Tests/Services/Regions/RegionAdministrationServiceTests.cs
- EPlast/EPlast.Tests/Services/Regions/RegionAnnualReportServiceTest.cs
> Regions and Events new tests 

- EPlast/EPlast.BLL/Services/Club/ClubService.cs
- EPlast/EPlast.Tests/Controllers/CityControllerTests.cs
- EPlast/EPlast.Tests/Controllers/ClubControllerTests.cs
- EPlast/EPlast.Tests/Services/City/CityAdministrationServiceTests.cs
- EPlast/EPlast.Tests/Services/City/CityDocumentsServiceTest.cs
- EPlast/EPlast.Tests/Services/City/CityMembersServiceTests.cs
- EPlast/EPlast.Tests/Services/City/CityServiceTests.cs
- EPlast/EPlast.Tests/Services/Club/ClubDocumentsServiceTest.cs
- EPlast/EPlast.Tests/Services/Club/ClubParticipantsServiceTests.cs
- EPlast/EPlast.Tests/Services/Club/ClubServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
> Adding unit-tests for City

- .gitignore
- EPlast/EPlast.Tests/Controllers/AnnualReportControllerTests.cs
- EPlast/EPlast.Tests/Controllers/AuthControllerTests.cs
> Added Annual report tests

- EPlast/EPlast.Tests/Controllers/AuthControllerTests.cs
> Added AuthControllerTests

- EPlast/EPlast.WebApi/StartupExtensions/AddSwaggerExtension.cs
> Fix swagger

- EPlast/EPlast.BLL/Services/Auth/AuthService.cs
- EPlast/EPlast.WebApi/Startup.cs
> Added role for RegisterUser

- EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
> Decisions blanks

- EPlast/EPlast.Tests/Services/Club/ClubAnnualReportServiceTests.cs
> addedNewTestsForClubAnnualReportService

- EPlast/EPlast.Tests/Services/City/CityServiceTests.cs
- EPlast/EPlast.Tests/Services/Club/ClubServiceTests.cs
> Add unit-tests for GetProfile methods in City and Club services.

- EPlast/EPlast.Tests/Services/City/CityParticipantsServiceTests.cs
> AddedNewTestsAddFollower

- EPlast/EPlast.BLL/DTO/UserProfiles/UserProfileDTO.cs
- EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserProfile.cs
- EPlast/EPlast.DataAccess/Migrations/20201229203648_AddPseudoToUserProfile.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20201229203648_AddPseudoToUserProfile.cs
- EPlast/EPlast.WebApi/Controllers/UserController.cs
- EPlast/EPlast.WebApi/Mapping/User/UserProfile.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserViewModel.cs
> Add pseudo, mail, city, club to UserProfile

- EPlast/EPlast.BLL/EPlast.BLL.csproj
- EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/RegionsController.cs
- EPlast/EPlast.WebApi/EPlast.WebApi.csproj
- EPlast/EPlast.WebApi/Extensions/DistributedCacheExtensions.cs
- EPlast/EPlast.WebApi/Startup.cs
- EPlast/EPlast.WebApi/appsettings.json
> Implement redis

- EPlast/EPlast.BLL/Services/Decision/DecisionService.cs
- EPlast/EPlast.Tests/Services/Blank/BlankAchievementsServiceTest.cs
- EPlast/EPlast.WebApi/Controllers/AdminController.cs
- EPlast/EPlast.WebApi/Controllers/AnnualReportController.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
- EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
- EPlast/EPlast.WebApi/Controllers/DistinctionController.cs
- EPlast/EPlast.WebApi/Controllers/EducatorsStaffController.cs
- EPlast/EPlast.WebApi/Controllers/StatisticsController.cs
> Edited access layers

- EPlast/EPlast.BLL/DTO/UserProfiles/UserDTO.cs
- EPlast/EPlast.BLL/DTO/UserProfiles/UserProfileDTO.cs
- EPlast/EPlast.DataAccess/EPlast.DataAccess.csproj
- EPlast/EPlast.DataAccess/Entities/UserEntities/User.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserProfile.cs
- EPlast/EPlast.DataAccess/Migrations/20210105135145_AddPublicPoliticalActivityToUserProfile.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210105135145_AddPublicPoliticalActivityToUserProfile.cs
- EPlast/EPlast.DataAccess/Migrations/EPlastDBContextModelSnapshot.cs
- EPlast/EPlast.WebApi/Mapping/User/UserProfile.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserViewModel.cs
> Add PublicPoliticalActivity field, make Adress, PhoneNumber and Birthday fields required

- EPlast/EPlast.BLL/Services/MethodicDocument/MethodicDocumentService.cs
> FixDocumentName

- EPlast/EPlast.BLL/DTO/UserProfiles/UpuDegreeDTO.cs
- EPlast/EPlast.BLL/DTO/UserProfiles/UserProfileDTO.cs
- EPlast/EPlast.BLL/Interfaces/UserProfiles/IUserPersonalDataService.cs
- EPlast/EPlast.BLL/Mapping/UserProfile/UpuDegreeProfile.cs
- EPlast/EPlast.BLL/Services/Auth/AuthService.cs
- EPlast/EPlast.BLL/Services/UserProfiles/UserPersonalDataService.cs
- EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
- EPlast/EPlast.DataAccess/EPlast.DataAccess.csproj
- EPlast/EPlast.DataAccess/EPlastDBContext.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UpuDegree.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/User.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserProfile.cs
- EPlast/EPlast.DataAccess/Migrations/20210114140147_AddUpuDegrees.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210114140147_AddUpuDegrees.cs
- EPlast/EPlast.DataAccess/Repositories/Interfaces/Base/IRepositoryWrapper.cs
- EPlast/EPlast.DataAccess/Repositories/Interfaces/User/IUpuDegreeRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Base/RepositoryWrapper.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/User/UpuDegreeRepository.cs
- EPlast/EPlast.WebApi/Controllers/UserController.cs
- EPlast/EPlast.WebApi/Mapping/User/UserProfile.cs
- EPlast/EPlast.WebApi/Mapping/User/UserProfileFields/UpuDegreeProfile.cs
- EPlast/EPlast.WebApi/Models/UserModels/EditUserViewModel.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserInfoViewModel.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserProfileFields/UpuDegreeViewModel.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserViewModel.cs
> Add UPU Degrees

- EPlast/EPlast.BLL/DTO/UserProfiles/UserProfileDTO.cs
- EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
- EPlast/EPlast.DataAccess/EPlast.DataAccess.csproj
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserProfile.cs
- EPlast/EPlast.DataAccess/Migrations/20210116202236_AddUserLinks.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210116202236_AddUserLinks.cs
- EPlast/EPlast.WebApi/Mapping/User/UserProfile.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserViewModel.cs
> Add User Social Media links

- EPlast/EPlast.BLL/DTO/UserProfiles/UserPrecautionDTO.cs
- EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserPrecaution.cs
- EPlast/EPlast.DataAccess/Migrations/20210118140838_add_precaution_status.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210118140838_add_precaution_status.cs
> AddingPrecautionStatuses

- EPlast/EPlast.BLL/Services/Region/RegionAnnualReportService.cs
> Fixed region annual report

- EPlast/EPlast.BLL/DTO/UserProfiles/UserPrecautionDTO.cs
- EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserPrecaution.cs
- EPlast/EPlast.DataAccess/Migrations/20210127092128_Adding-Precautions-EndDate-IsActive.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210127092128_Adding-Precautions-EndDate-IsActive.cs
- EPlast/EPlast.Tests/Services/Precautions/UserPrecautionServiceTests.cs
> AddingPrecautionsEndDate

- EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
- EPlast/EPlast.WebApi/Controllers/UserController.cs
- EPlast/EPlast.WebApi/Mapping/User/UserInfoProfile.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserInfoViewModel.cs
> New links logic had made and bugs with UPU and Approvers had fixed

- EPlast/EPlast.WebApi/Controllers/UserController.cs
> Fix IsUserPlastun check

- EPlast/EPlast.BLL/DTO/UserProfiles/ShortUserInformationDTO.cs
> ShortUser fixed

- EPlast/EPlast.Resources/AuthenticationErrors.uk.resx
- EPlast/EPlast.Tests/Controllers/AuthControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/AdminController.cs
- EPlast/EPlast.WebApi/Controllers/AuthController.cs
> Added ResendEmailRegistr

- EPlast/EPlast/appsettings.json
> New appsettings for MVC

- EPlast/EPlast.WebApi/EPlast.WebApi.csproj
- EPlast/EPlast.WebApi/Startup.cs
- EPlast/EPlast.WebApi/appsettings.json
> Implement Secrets

- EPlast/EPlast.BLL/Interfaces/Precautions/IUserPrecautionService.cs
- EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
- EPlast/EPlast.Tests/Controllers/PrecautionControllerTests.cs
- EPlast/EPlast.Tests/Services/Precautions/UserPrecautionServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/PrecautionController.cs
> Adding filters for users without precautions

- EPlast/EPlast.WebApi/appsettings.json
> Delete wrong space

- EPlast/EPlast.BLL/Services/Auth/AuthEmailService.cs
> no message

- EPlast/EPlast.BLL/Services/Auth/AuthService.cs
> Fix miss delete

- EPlast/EPlast.WebApi/Startup.cs
- EPlast/EPlast.WebApi/appsettings.json
> Add DB connection string to secrets

- EPlast/EPlast.BLL/Services/Auth/AuthService.cs
> It doesn`t work without this

- EPlast/EPlast.WebApi/Controllers/DistinctionController.cs
- EPlast/EPlast.WebApi/Controllers/EducatorsStaffController.cs
- EPlast/EPlast.WebApi/Controllers/PrecautionController.cs
> Add "Зареєстрований користувач" to Authorize roles

- EPlast/EPlast.BLL/Services/Auth/AuthEmailService.cs
> Fixed reminder text

- EPlast/EPlast.WebApi/StartupExtensions/AddServicesExtension.cs
> Try to correct localization

- EPlast/EPlast.Resources/EPlast.Resources.csproj
- EPlast/EPlast.WebApi/Startup.cs
> Changed access to public

- EPlast/EPlast.WebApi/Startup.cs
- EPlast/EPlast.WebApi/StartupExtensions/AddServicesExtension.cs
> Fixed startup Configure method

- EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
- EPlast/EPlast.DataAccess/Repositories/Interfaces/Base/IRepositoryWrapper.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Base/RepositoryWrapper.cs
- EPlast/EPlast.Tests/Services/City/CityParticipantsServiceTests.cs
- EPlast/EPlast.WebApi/appsettings.json
> City approve email notification

- EPlast/EPlast.Tests/EPlast.Tests.csproj
- EPlast/EPlast.WebApi/EPlast.WebApi.csproj
- EPlast/EPlast.WebApi/Startup.cs
- EPlast/EPlast.WebApi/StartupExtensions/AddServicesExtension.cs
> Removed wrong dependencies

- EPlast/EPlast.BLL/Services/Auth/AuthService.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserProfile.cs
> Implement better realization of default UPUDegreeID

- EPlast/EPlast.BLL/Interfaces/ConfirmedUsers/IConfirmedUsersService.cs
- EPlast/EPlast.BLL/Services/ConfirmedUsers/ConfirmedUsersService.cs
- EPlast/EPlast.DataAccess/EPlastDBContext.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/User.cs
- EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
- EPlast/EPlast.Tests/Services/Club/ClubServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/UserController.cs
- EPlast/EPlast.WebApi/EPlast.WebApi.csproj
- EPlast/EPlast.XUnitTest/Services/Club/ClubServiceTests.cs
- EPlast/EPlast.XUnitTest/Services/UserArea/ConfirmedUsersServiceTests.cs
> Added email sending

- EPlast/EPlast.DataAccess/EPlastDBContext.cs
> removed new Users

- EPlast/EPlast.DataAccess/EPlastDBContext.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/User.cs
- EPlast/EPlast.WebApi/EPlast.WebApi.csproj
> Returned cityName, razorpage

- EPlast/EPlast.BLL/Services/ConfirmedUsers/ConfirmedUsersService.cs
- EPlast/EPlast.DataAccess/EPlastDBContext.cs
> User vauching email notification

- EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
> Added more tests for AdminnController

- EPlast/EPlast.WebApi/Models/UserModels/UserProfileFields/DegreeViewModel.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserProfileFields/WorkViewModel.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserViewModel.cs
> Changed Regexes

- EPlast/EPlast.Tests/Controllers/AuthControllerTests.cs
- EPlast/EPlast.Tests/Controllers/PasswordControllerTests.cs
- EPlast/EPlast.Tests/Controllers/PrecautionControllerTests.cs
- EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
> Fixed tests

- EPlast/EPlast.BLL/Services/EmailSending/NewPlastMemberEmailGreetingService.cs
- EPlast/EPlast.BLL/Services/Events/ActionManager.cs
- EPlast/EPlast.BLL/Services/Events/EventGalleryManager.cs
- EPlast/EPlast.Tests/Controllers/DistinctionControllerTests.cs
- EPlast/EPlast.Tests/Controllers/EventsControllerTests.cs
- EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/EventsController.cs
> Test for event controller

- EPlast/EPlast.Tests/Controllers/EventCalendarControllerTests.cs
- EPlast/EPlast.Tests/Controllers/GoverningBodiesControllerTests.cs
- EPlast/EPlast.Tests/Controllers/NotificationBoxControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/StatisticsController.cs
> Wrong tests fix

- EPlast/EPlast.BLL/DTO/ActiveMembership/AccessLevelTypeDTO.cs
- EPlast/EPlast.BLL/DTO/ActiveMembership/RolesForActiveMembershipTypeDTO.cs
- EPlast/EPlast.BLL/Services/ActiveMembership/AccessLevelService.cs
- EPlast/EPlast.Tests/Services/ActiveMembership/AccessLevelServiceTests.cs
> Access levels service fixes

- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
- EPlast/EPlast.BLL/Services/Precautions/PrecautionService.cs
> fixed codesmells

- EPlast/EPlast.BLL/Interfaces/Admin/IAdminService.cs
- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
> quick fixes

- EPlast/EPlast.DataAccess/EPlastDBContext.cs
> fixed bug on userTable

- EPlast/EPlast.Tests/Controllers/ActiveMembershipControllerTests.cs
- EPlast/EPlast.Tests/Controllers/EducatorsStaffControllerTests.cs
- EPlast/EPlast.Tests/Controllers/NotificationBoxControllerTests.cs
- EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
- EPlast/EPlast.Tests/Services/Blank/BlankAchievementsServiceTest.cs
- EPlast/EPlast.Tests/Services/City/CityDocumentsServiceTest.cs
- EPlast/EPlast.Tests/Services/City/CityServiceTests.cs
- EPlast/EPlast.Tests/Services/Club/ClubAccess/ClubAccessServiceTest.cs
- EPlast/EPlast.XUnitTest/Services/AnnualReport/AnnualReportServiceTests.cs
- EPlast/EPlast.XUnitTest/Services/Decision/DecisionServiceTests.cs
- EPlast/EPlast.XUnitTest/Services/Events/ActionManagerTests.cs
- EPlast/EPlast.XUnitTest/Services/Events/EventCategoryManagerTests.cs
- EPlast/EPlast.XUnitTest/Services/Events/EventGalleryManagerTests.cs
- EPlast/EPlast.XUnitTest/Services/Events/EventStatusManagerTests.cs
- EPlast/EPlast.XUnitTest/Services/Events/EventTypeManagerTests.cs
- EPlast/EPlast.XUnitTest/Services/Events/ParticipantManagerTests.cs
> fixed bugs on xUnit tests

- EPlast/EPlast.AutomatedTest/ExampleTest.cs
- EPlast/EPlast.Tests/Services/Club/ClubDocumentsServiceTest.cs
- EPlast/EPlast.Tests/Services/Club/ClubParticipantsServiceTests.cs
- EPlast/EPlast.Tests/Services/Decision/DecisionsServiceTest.cs
- EPlast/EPlast.Tests/Services/DistinctionServiceTest/DistinctionServiceTests.cs
- EPlast/EPlast.Tests/Services/DistinctionServiceTest/UserDistinctionServiceTests.cs
- EPlast/EPlast.Tests/Services/EducatorStaff/EducatorsStaffTypesServiceTests.cs
- EPlast/EPlast.Tests/Services/Event/EventCalendarServiceTests.cs
- EPlast/EPlast.Tests/Services/Event/EventsManagerTests.cs
- EPlast/EPlast.XUnitTest/Services/Events/ParticipantStatusManagerTests.cs
> Fixed more code smells

- EPlast/EPlast.Tests/Services/Event/EventsManagerTests.cs
- EPlast/EPlast.Tests/Services/GoverningBodiesServiceTests.cs
- EPlast/EPlast.Tests/Services/Precautions/PrecautionServiceTests.cs
- EPlast/EPlast.Tests/Services/Precautions/UserPrecautionServiceTests.cs
- EPlast/EPlast.Tests/Services/Regions/RegionAdministrationServiceTests.cs
- EPlast/EPlast.XUnitTest/Services/Authentication/AccountServiceTests.cs
- EPlast/EPlast.XUnitTest/Services/City/CityServiceTests.cs
- EPlast/EPlast.XUnitTest/Services/UserArea/UserServiceTests.cs
- EPlast/EPlast.XUnitTest/Services/UserProfiles/UserPersonalDataServiceTests.cs
> Fix all code smells

- EPlast/EPlast.BLL/Interfaces/Admin/IAdminService.cs
- EPlast/EPlast.BLL/Interfaces/Precautions/IUserPrecautionService.cs
- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
- EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
- EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
- EPlast/EPlast.Tests/Controllers/PrecautionControllerTests.cs
- EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
- EPlast/EPlast.Tests/Services/Precautions/UserPrecautionServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/AdminController.cs
- EPlast/EPlast.WebApi/Controllers/PrecautionController.cs
> 500StatusCode errors fix

- EPlast/EPlast.BLL/DTO/Admin/TableFilterParameters.cs
- EPlast/EPlast.BLL/Interfaces/Admin/IAdminService.cs
- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
- EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
- EPlast/EPlast.DataAccess/Repositories/Interfaces/Admin/IAdminTypeRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Admin/AdminTypeRepository.cs
- EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
- EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
- EPlast/EPlast.Tests/Services/Precautions/UserPrecautionServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/AdminController.cs
> Plast degree fix

- EPlast/EPlast.BLL/Interfaces/Admin/IAdminService.cs
- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
- EPlast/EPlast.BLL/Services/Auth/AuthService.cs
- EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
- EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/AdminController.cs
- EPlast/EPlast.WebApi/Mapping/Decision/DecisionProfile.cs
- EPlast/EPlast.WebApi/Models/Decision/DecisionViewModel.cs
> Decisions updates

- EPlast/EPlast.Tests/Services/Admin/AdminTypeServiceTests.cs
> Added tests for AdminTypeService

- EPlast/EPlast.DataAccess/EPlastDBContext.cs
> Restored entities for stored procedures

- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
> Aceess levels 

- EPlast/EPlast.Resources/Roles.cs
- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
> Changed roles for controller

- EPlast/EPlast.Resources/Roles.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
> Add new role change controller

- EPlast/EPlast.Tests/Services/UserManager/UserManagerServiceTests.cs
> Added Tests for UserManagerService

- EPlast/EPlast.Tests/Services/UserProfiles/UserServiceTests.cs
> Added Tests for UserService

- EPlast/EPlast.BLL/Interfaces/Notifications/INotificationConnectionManager.cs
- EPlast/EPlast.BLL/Interfaces/Notifications/IUserMapService.cs
- EPlast/EPlast.BLL/Services/Notifications/NotificationConnectionManager.cs
- EPlast/EPlast.BLL/Services/Notifications/UserMapService.cs
- EPlast/EPlast.Tests/Services/Notifications/NotificationConnectionManagerTests.cs
- EPlast/EPlast.Tests/Services/Notifications/UserMapServiceTests.cs
- EPlast/EPlast.WebApi/StartupExtensions/AddDependenciesExtension.cs
- EPlast/EPlast.WebApi/WebSocketHandlers/BaseWebSocketHandler.cs
dev
ToDo
Rewrited notificationConnectionManager class and added Unit tests for methods
ToDo
> Rewrite_NotofocationConnectionManager

- EPlast/EPlast.BLL/DTO/UserProfiles/UserTableDTO.cs
> Fix small bug

- EPlast/EPlast.WebApi/web.config
> Added web.config to fix GoverningBodies

- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
- EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
- EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
> Various Bug fixes

- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
> New logic for register user

- EPlast/EPlast.WebApi/Models/UserModels/UserProfileFields/GenderViewModel.cs
> Fixing_bug_with_gender_field

- EPlast/EPlast.WebApi/Controllers/DistinctionController.cs
> Restored missing endpoint in DistinctionController

- EPlast/EPlast.BLL/DTO/UserProfiles/UserTableDTO.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserTableObject.cs
- EPlast/EPlast.WebApi/Controllers/ActiveMembershipController.cs
- EPlast/EPlast.WebApi/Controllers/AnnualReportController.cs
- EPlast/EPlast.WebApi/Mapping/User/UserInfoProfile.cs
- EPlast/EPlast.WebApi/Mapping/User/UserShortProfile.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserInfoViewModel.cs
> Fixed bugs

- EPlast/EPlast.BLL/Services/Events/ParticipantManager.cs
- EPlast/EPlast.XUnitTest/Services/Events/ParticipantManagerTests.cs
> Fix_bug_with_wrong_event_quantity

- EPlast/EPlast.BLL/Interfaces/PDF/IPDFService.cs
- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
- EPlast/EPlast.BLL/Services/PDF/Documents/MethodicDocumentPdf.cs
- EPlast/EPlast.BLL/Services/PDF/PDFService.cs
- EPlast/EPlast.Tests/Controllers/MethodicDocumentsCintrollerTests.cs
- EPlast/EPlast.Tests/Services/PDF/PDFServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/MethodicDocumentsController.cs
> Lower role determination update and pdf convertation for MethodicDocuments

- EPlast/EPlast.DataAccess/Entities/UserEntities/Degree.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/Work.cs
- EPlast/EPlast.DataAccess/Migrations/20210530132825_ChangeLengthOfWorksPosition.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210530132825_ChangeLengthOfWorksPosition.cs
- EPlast/EPlast.DataAccess/Migrations/20210530133304_ChangeLengthOfWorksPlaceOfwork.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210530133304_ChangeLengthOfWorksPlaceOfwork.cs
- EPlast/EPlast.DataAccess/Migrations/20210530133500_ChangeLengthOfDegreeName.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210530133500_ChangeLengthOfDegreeName.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserProfileFields/DegreeViewModel.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserProfileFields/EducationViewModel.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserProfileFields/WorkViewModel.cs
> ChangedSomeFields

- EPlast/EPlast.BLL/DTO/Region/RegionAnnualReportDTO.cs
> Region reports

- EPlast/EPlast.Tests/Controllers/EventsControllerTests.cs
- EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
> Added EventsController and UserController tests

- .env
- EPlast/EPlast.Tests/Controllers/AnnualReportControllerTests.cs
- EPlast/EPlast.Tests/Controllers/EducatorsStaffControllerTests.cs
- EPlast/EPlast.Tests/Controllers/PasswordControllerTests.cs
- EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
- EPlast/EPlast.WebApi/EPlast.WebApi.csproj
dev
ToDo tests to regions controler and added several tests to other controllers
ToDo
ToDo
> add_tests to regions controler cover 100%

- EPlast/EPlast.WebApi/EPlast.WebApi.csproj
> Fixed bug with nullable

- EPlast/EPlast.BLL/DTO/MethodicDocument/MethodicDocumentTypeDTO.cs
> Changes description of one methodic document type

- EPlast/EPlast.BLL/DTO/UserProfiles/UserTableDTO.cs
- EPlast/EPlast.BLL/Interfaces/UserProfiles/IUserService.cs
- EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserTableObject.cs
- EPlast/EPlast.Resources/Roles.cs
- EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
- EPlast/EPlast.Tests/Services/UserProfiles/UserServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/UserController.cs
- EPlast/EPlast.WebApi/Mapping/User/UserInfoProfile.cs
- EPlast/EPlast.WebApi/Mapping/User/UserProfile.cs
- EPlast/EPlast.WebApi/Mapping/User/UserShortProfile.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserApproversViewModel.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserInfoViewModel.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserShortViewModel.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserViewModel.cs
- EPlast/EPlast.XUnitTest/Services/UserArea/UserServiceTests.cs
> Bugs user table

- EPlast/EPlast.BLL/Services/PDF/Documents/PdfDocument.cs
- EPlast/EPlast.BLL/Services/PDF/PDFHelper.cs
- EPlast/EPlast.BLL/Services/PDF/PDFService.cs
> Added encoding to title of pdf document

- EPlast/EPlast.BLL/DTO/City/CityDTO.cs
- EPlast/EPlast.BLL/DTO/Region/RegionProfileDTO.cs
- EPlast/EPlast.BLL/Services/City/CityService.cs
- EPlast/EPlast.BLL/Services/Region/RegionService.cs
- EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
- EPlast/EPlast.WebApi/Mapping/City/CityProfile.cs
- EPlast/EPlast.WebApi/Models/City/CityViewModel.cs
- EPlast/EPlast.WebApi/Properties/launchSettings.json
- EPlast/EPlast.WebApi/appsettings.json
> Impoved document section

- EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
> Fixed bug with email notifications for city head and city head deputy

- EPlast/EPlast.BLL/Services/Auth/AuthEmailService.cs
> Fixed url in greeting email

- EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
> Fix Delete City Admins

- EPlast/EPlast.Resources/AuthenticationErrors.en.resx
- EPlast/EPlast.Resources/AuthenticationErrors.uk.resx
- EPlast/EPlast.Tests/Controllers/AuthControllerTests.cs
> Change notification text

- EPlast/EPlast.WebApi/AccessSecurityModel/GoverningBodyAccessSettings.json
> Add user access for creating governing body sectors

- EPlast/EPlast.BLL/Interfaces/GoverningBodies/IGoverningBodiesService.cs
- EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
- EPlast/EPlast.BLL/Services/Club/ClubParticipantsService.cs
- EPlast/EPlast.BLL/Services/GoverningBodies/GoverningBodiesService.cs
- EPlast/EPlast.BLL/Services/Region/RegionAdministrationService.cs
- EPlast/EPlast.Tests/Controllers/GoverningBodiesControllerTests.cs
- EPlast/EPlast.Tests/Services/GoverningBody/GoverningBodiesServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> Display the role of the governing body in secretaries ( "Діловодства" )tab  

- EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
- EPlast/EPlast.BLL/Services/Club/ClubParticipantsService.cs
- EPlast/EPlast.BLL/Services/GoverningBodies/GoverningBodiesService.cs
- EPlast/EPlast.BLL/Services/Region/RegionAdministrationService.cs
> Display Former Secretaries in descending order

- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
- EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> Fixed access levels for registered user

- EPlast/EPlast.BLL/DTO/GoverningBody/GoverningBodyAdministrationDTO.cs
- EPlast/EPlast.BLL/Services/GoverningBodies/GoverningBodyAdministrationService.cs
- EPlast/EPlast.DataAccess/Entities/GoverningBody/GoverningBodyAdministration.cs
- EPlast/EPlast.DataAccess/Migrations/20210715071809_AddWorkEmailToGoverningBodyAdmin.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210715071809_AddWorkEmailToGoverningBodyAdmin.cs
- EPlast/EPlast.WebApi/Models/GoverningBody/GoverningBodyAdministrationViewModel.cs
> Add work email column to governing body admins table

- EPlast/EPlast.Tests/Controllers/GoverningBodiesControllerTests.cs
- EPlast/EPlast.Tests/Controllers/GoverningBodySectorsControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
- EPlast/EPlast.WebApi/Controllers/GoverningBodySectorsController.cs
> Set documents count for response

- EPlast/EPlast.WebApi/AccessSecurityModel/GoverningBodyAccessSettings.json
- EPlast/EPlast.WebApi/AccessSecurityModel/GoverningBodySectorAccessSettings.json
> Fix accesses for Region Head on Governing Bodies

- EPlast/EPlast.BLL/Interfaces/Club/IClubParticipantsService.cs
- EPlast/EPlast.BLL/Services/Club/ClubParticipantsService.cs
- EPlast/EPlast.Tests/Controllers/ClubControllerTests.cs
- EPlast/EPlast.Tests/Services/Club/ClubParticipantsServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
> Fix adding admin with past date

- EPlast/EPlast.BLL/Services/PDF/Documents/BlankDocument.cs
> Fixed [Blank] There is no indent near some fields in "Заява для вступ…у" #1515

- EPlast/EPlast.BLL/DTO/Club/ClubDTO.cs
- EPlast/EPlast.BLL/Services/PDF/Documents/BlankDocument.cs
- EPlast/EPlast.DataAccess/Entities/Club/Club.cs
- EPlast/EPlast.DataAccess/Migrations/20210804140917_ChangedClubNameMaxLength.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210804140917_ChangedClubNameMaxLength.cs
> Added migration to change attribute on Club Name

- EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> Fixed access to regions for all users

- EPlast/EPlast.BLL/DTO/Blank/AchievementDocumentsDTO.cs
- EPlast/EPlast.BLL/DTO/Blank/BlankBiographyDocumentsDTO.cs
- EPlast/EPlast.BLL/DTO/Blank/ExtractFromUPUDocumentsDTO.cs
- EPlast/EPlast.DataAccess/Entities/Blank/AchievementDocuments.cs
- EPlast/EPlast.DataAccess/Entities/Blank/BlankBiographyDocuments.cs
- EPlast/EPlast.DataAccess/Entities/Blank/ExtractFromUPUDocuments.cs
- EPlast/EPlast.DataAccess/Entities/City/CityDocuments.cs
- EPlast/EPlast.DataAccess/Entities/Club/ClubDocuments.cs
- EPlast/EPlast.DataAccess/Entities/GoverningBody/GoverningBodyDocuments.cs
- EPlast/EPlast.DataAccess/Entities/GoverningBody/Sector/SectorDocuments.cs
- EPlast/EPlast.DataAccess/Migrations/20210809134307_DeleteFileNameLength.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210809134307_DeleteFileNameLength.cs
> Delete attribute Required on several fileNames

- EPlast/EPlast.BLL/Services/Club/ClubService.cs
> Fix club admins with past date display

- EPlast/EPlast.WebApi/Mapping/User/UserInfoProfile.cs
- EPlast/EPlast.WebApi/Mapping/User/UserProfile.cs
- EPlast/EPlast.WebApi/Mapping/User/UserShortProfile.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserViewModel.cs
> fixed-bug on Personal profile 

- EPlast/EPlast.BLL/DTO/ActiveMembership/AccessLevelTypeDTO.cs
- EPlast/EPlast.BLL/Services/ActiveMembership/AccessLevelService.cs
- EPlast/EPlast.Resources/Degree.cs
- EPlast/EPlast.Resources/Roles.cs
- EPlast/EPlast.Tests/Services/ActiveMembership/AccessLevelServiceTests.cs
> Changed access levels service

- EPlast/EPlast.BLL/Interfaces/Region/IRegionService.cs
- EPlast/EPlast.BLL/Services/Region/RegionService.cs
- EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
- EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
- EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> Created check for region name exists functionality

- EPlast/EPlast.WebApi/AccessSecurityModel/RegionsBoardAccessSettings.json
> Fixed [Regional Board of the Plast ] The Deputy of Village Admin or Country Admin does not have access to decision #1690

- EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> Fixed path to the controller

- EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/LoginController.cs
> Added check for former member when login in

- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
- EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> Fixed needed level for approving or removing region follower

- EPlast/EPlast.BLL/DTO/MethodicDocument/MethodicDocumentDTO.cs
- EPlast/EPlast.DataAccess/Entities/MethodicDocument/MethodicDocument.cs
- EPlast/EPlast.DataAccess/Migrations/20210908214520_AddMaxLenghtToDescriptionInMethodicDocument.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210908214520_AddMaxLenghtToDescriptionInMethodicDocument.cs
> Added max length to short description in Legislation(Repository)

- EPlast/EPlast.Resources/Roles.cs
- EPlast/EPlast.WebApi/AccessSecurityModel/GoverningBodyAccessSettings.json
- EPlast/EPlast.WebApi/Controllers/AdminController.cs
- EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
- EPlast/EPlast.WebApi/Controllers/GoverningBodySectorsController.cs
> Fixed bug when GBHeads could not add new user to GB, edit GB and manage GB sectors

- EPlast/EPlast.BLL/Services/GoverningBodies/GoverningBodyAdministrationService.cs
- EPlast/EPlast.Tests/Controllers/GoverningBodiesControllerTests.cs
- EPlast/EPlast.Tests/Services/GoverningBody/GoverningBodyAdministrationServiceTests.cs
- EPlast/EPlast.WebApi/AccessSecurityModel/GoverningBodyAccessSettings.json
- EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> Restricted for admins access to add lowrole users

- EPlast/EPlast.BLL/DTO/UserProfiles/EducationDTO.cs
- EPlast/EPlast.DataAccess/EPlast.DataAccess.csproj
- EPlast/EPlast.DataAccess/Entities/UserEntities/Education.cs
- EPlast/EPlast.DataAccess/Migrations/20210912105553_IncreaseMaxLenghtPlaceOfStudy.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210912105553_IncreaseMaxLenghtPlaceOfStudy.cs
- EPlast/EPlast.Tests/Controllers/AboutBaseControllerTests.cs
- EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
> Unit tests fors AdminController, AboutBaseController and migration  max length (50 ->100) placeOfStudy

- EPlast/EPlast.DataAccess/EPlastDBContext.cs
- EPlast/EPlast.DataAccess/Migrations/20210914081947_AddConstraintGenderTable.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20210914081947_AddConstraintGenderTable.cs
- EPlast/EPlast.WebApi/Controllers/UserController.cs
> Fix possibility to enter any gender via Postman (fix#1190)

- EPlast/EPlast.BLL/Services/EventUser/EventUserManager.cs
- EPlast/EPlast.BLL/Services/Events/ActionManager.cs
- EPlast/EPlast.BLL/Services/Events/ParticipantManager.cs
> changed statuses' names for events

- EPlast/EPlast.BLL/Interfaces/GoverningBodies/Announcement/IGoverningBodyAnnouncementService.cs
- EPlast/EPlast.BLL/Services/GoverningBodies/Announcement/GoverningBodyAnnouncementService.cs
- EPlast/EPlast.Tests/Controllers/GoverningBodiesControllerTests.cs
- EPlast/EPlast.Tests/Services/GoverningBody/Announcement/GoverningBodyAnnouncementServiceTest.cs
- EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
> Added announcement editing

- EPlast/EPlast.Resources/AuthenticationErrors.en.resx
- EPlast/EPlast.Resources/AuthenticationErrors.uk.resx
- EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
> Changed notification text #1786

- EPlast/EPlast.BLL/Services/EmailSending/EmailContentService.cs
> Fixed notifications' text #1737

- EPlast/EPlast.BLL/Services/GoverningBodies/GoverningBodiesService.cs
- EPlast/EPlast.BLL/Services/GoverningBodies/Sector/SectorService.cs
- EPlast/EPlast.Tests/Services/GoverningBody/GoverningBodiesServiceTests.cs
- EPlast/EPlast.Tests/Services/GoverningBody/Sector/SectorServiceTests.cs
> Fixed removing governing body with admins

- EPlast/EPlast.BLL/DTO/ActiveMembership/UserMembershipDatesDTO.cs
- EPlast/EPlast.Resources/AllowedDates.cs
- EPlast/EPlast.WebApi/Controllers/ActiveMembershipController.cs
> Restricted possibility to add wrong active membership dates via Postman (Fix bug #1843)

- EPlast/EPlast.WebApi/Controllers/PrecautionController.cs
> Disabled possibility to get precautions using registered user token ( Fix bug #1847 )

- EPlast/EPlast.BLL/Interfaces/GoverningBodies/Sector/ISectorService.cs
- EPlast/EPlast.BLL/Services/GoverningBodies/Sector/SectorAdministrationService.cs
- EPlast/EPlast.BLL/Services/GoverningBodies/Sector/SectorService.cs
- EPlast/EPlast.Tests/Controllers/GoverningBodySectorsControllerTests.cs
- EPlast/EPlast.Tests/Services/GoverningBody/Sector/SectorAdministrationServiceTests.cs
- EPlast/EPlast.Tests/Services/GoverningBody/Sector/SectorServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/GoverningBodySectorsController.cs
> Added admingetter for sectors

- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
- EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
> Added removing admin previlege before becoming former member

- manifests/deployment.yml
- manifests/redis-master-deployment.yaml
> Add HorizontalPodAutoscaler and configure pod resource limits

- manifests/deployment.yml
- manifests/redis-master-deployment.yaml
> Update resource limits

- manifests/deployment.yml
- manifests/redis-master-deployment.yaml
> Update memory limit and replica count

- EPlast/EPlast.WebApi/Models/UserModels/UserViewModel.cs
> Changed wrong regular expression for phone number 

- EPlast/EPlast.BLL/DTO/Club/ClubForAdministrationDTO.cs
- EPlast/EPlast.BLL/DTO/Region/RegionForAdministrationDTO.cs
- EPlast/EPlast.Tests/Services/Club/ClubAccess/ClubAccessServiceTest.cs
- EPlast/EPlast.Tests/Services/Regions/RegionAccessServiceTest.cs
> added isActive prop to DTO

- EPlast/EPlast.DataAccess/Repositories/Realizations/Region/RegionRepository.cs
- EPlast/EPlast.Tests/Controllers/ClubControllerTests.cs
- EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
> Remove possibility to delete or update hovel or city

- EPlast/EPlast.BLL/Services/Club/ClubParticipantsService.cs
- EPlast/EPlast.Tests/Services/Club/ClubParticipantsServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
> fix bug #1855

- EPlast/EPlast.BLL/Services/City/CityService.cs
> remove takes from GetCityProfyleAsync

- EPlast/EPlast.BLL/Services/GoverningBodies/GoverningBodiesService.cs
> Fix code smell in governing body

- EPlast/EPlast.BLL/Services/City/CityService.cs
> add takes from GetCityProfyleAsync

- EPlast/EPlast.BLL/Services/GoverningBodies/GoverningBodiesService.cs
- EPlast/EPlast.BLL/Services/Region/RegionService.cs
- EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
- EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> Added blob storage for regions logo

- EPlast/EPlast.BLL/Interfaces/City/ICityService.cs
- EPlast/EPlast.BLL/Services/City/CityService.cs
- EPlast/EPlast.Tests/Controllers/CityControllerTests.cs
- EPlast/EPlast.Tests/Services/City/CityServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
> Add check plast member

- EPlast/EPlast.BLL/Services/City/CityService.cs
- EPlast/EPlast.BLL/Services/Club/ClubService.cs
> add 1 check

- EPlast/EPlast.BLL/Interfaces/AnnualReport/IAnnualReportAccessService.cs
- EPlast/EPlast.BLL/Interfaces/UserAccess/IUserAccessService.cs
- EPlast/EPlast.BLL/Services/AnnualReport/AnnualReportAccessService.cs
- EPlast/EPlast.BLL/Services/UserAccess/UserAccessService.cs
- EPlast/EPlast.Tests/Controllers/UserAccessControllerTests.cs
- EPlast/EPlast.Tests/Services/AnnualReport/AnnualReportAccessServiceTests.cs
- EPlast/EPlast.Tests/Services/UserAcccess/UserAccessServiceTests.cs
- EPlast/EPlast.WebApi/AccessSecurityModel/AnnualReportAccessSettings.json
- EPlast/EPlast.WebApi/Controllers/UserAccessController.cs
- EPlast/EPlast.WebApi/StartupExtensions/AddDependenciesExtension.cs
> added json accesses for annual reports

- EPlast/EPlast.BLL/DTO/ActiveMembership/AccessLevelTypeDTO.cs
- EPlast/EPlast.BLL/Services/ActiveMembership/AccessLevelService.cs
- EPlast/EPlast.BLL/Services/City/CityService.cs
- EPlast/EPlast.BLL/Services/Club/ClubService.cs
- EPlast/EPlast.BLL/Services/Region/RegionService.cs
- EPlast/EPlast.Resources/Roles.cs
- EPlast/EPlast.Tests/Services/City/CityServiceTests.cs
- EPlast/EPlast.Tests/Services/Club/ClubServiceTests.cs
- EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
> Restrictions for archivation

- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
- EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> Added authorization restrictions for archivating and deleting

- EPlast/EPlast.BLL/Services/EmailSending/NewPlastMemberEmailGreetingService.cs
> When a user became plast member, his role of supporter should be removed (Fixes #2037)

- EPlast/EPlast.WebApi/Controllers/AboutBaseController.cs
> Improve AboutBaseController

- EPlast/EPlast.WebApi/Controllers/MethodicDocumentsController.cs
> Fix bug that a registered user could add documents into legistation

- EPlast/EPlast.BLL/Services/EventUser/EventUserManager.cs
- EPlast/EPlast.Resources/AllowedRolesToBeAdminOfEvent.cs
- EPlast/EPlast.Resources/FunctionalityWithSpecificAccessForEvents.cs
- EPlast/EPlast.Tests/Services/Event/EventUserManagerTests.cs
- EPlast/EPlast.XUnitTest/Services/Events/EventUserManagerTests.cs
> Fix roles for event admin

- EPlast/EPlast.BLL/Services/UserProfiles/UserRenewalService.cs
> Removed oath date reset

- EPlast/EPlast.BLL/Interfaces/EventUser/IEventUserAccessService.cs
- EPlast/EPlast.BLL/Services/EventUser/EventUserAccess/EventUserAccessService.cs
- EPlast/EPlast.BLL/Services/EventUser/EventUserManager.cs
- EPlast/EPlast.BLL/Services/Events/ActionManager.cs
- EPlast/EPlast.BLL/Services/UserAccess/UserAccessService.cs
- EPlast/EPlast.Resources/FunctionalityWithSpecificAccessForEvents.cs
- EPlast/EPlast.Tests/Controllers/EventsControllerTests.cs
- EPlast/EPlast.Tests/Services/Event/EventUserAccessServiceTests.cs
- EPlast/EPlast.Tests/Services/UserAcccess/UserAccessServiceTests.cs
- EPlast/EPlast.WebApi/AccessSecurityModel/EventUserAccessSettings.json
dev
closes #2116
ToDo
ToDo
ToDo
> fixed user accesses for events

- EPlast/EPlast.BLL/Interfaces/EducatorsStaff/IEducatorsStaffService.cs
- EPlast/EPlast.BLL/Services/EducatorsStaff/EducatorsStaffService.cs
- EPlast/EPlast.DataAccess/EPlastDBContext.cs
- EPlast/EPlast.DataAccess/Entities/EducatorsStaff/EducatorsStaffTableObject.cs
- EPlast/EPlast.DataAccess/Repositories/Interfaces/EducatorsStaff/IEducatorsStaffRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/EducatorsStaff/EducatorsStaffRepository.cs
- EPlast/EPlast.Tests/Controllers/EducatorsStaffControllerTests.cs
- EPlast/EPlast.Tests/Services/EducatorStaff/EducatorsStaffServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/EducatorsStaffController.cs
> Added proper data getting for EducatorsStaff table (covers issue #2117)

- EPlast/EPlast.BLL/Services/City/CityAccess/CityAccessService.cs
- EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
- EPlast/EPlast.BLL/Services/City/CityService.cs
- EPlast/EPlast.BLL/Services/Club/ClubAccess/ClubAccessService.cs
- EPlast/EPlast.BLL/Services/Club/ClubParticipantsService.cs
- EPlast/EPlast.BLL/Services/PDF/Documents/TextFormatter.cs
- EPlast/EPlast.BLL/Services/Region/RegionAccess/RegionAccessService.cs
- EPlast/EPlast.BLL/Services/Statistics/StatisticsItems/Interfaces/MajorStatisticsItem.cs
- EPlast/EPlast.WebApi/Controllers/BlanksController.cs
- EPlast/EPlast.WebApi/Controllers/EventsUsersController.cs
- EPlast/EPlast.WebApi/Controllers/UserController.cs
- EPlast/EPlast.WebApi/appsettings.json
> Fixed a few code smells

- EPlast/EPlast.Resources/Roles.cs
- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
Editing city and club using Postman now requires role specified in access levels table.
dev
ToDo
ToDo
ToDo
> Postman bug fixed

- EPlast/EPlast.BLL/Services/Club/ClubService.cs
- EPlast/EPlast.Resources/Roles.cs
- EPlast/EPlast.Tests/Services/Club/ClubServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
Postman hovel creation and hovel administration bugs fixed.
ToDo
ToDo
ToDo
> Postman hovel creation fixed

- EPlast/EPlast.BLL/DTO/Decision/DecisionTargetDTO.cs
> fixed empty TargetName on add decision

- EPlast/EPlast.BLL/Interfaces/UserManager/IUserManagerService.cs
- EPlast/EPlast.BLL/Services/UserManager/UserManagerService.cs
- EPlast/EPlast.Tests/Services/UserManager/UserManagerServiceTests.cs
> Updated UserManagerService (improvements, additions, etc.)

- EPlast/EPlast.BLL/Services/AnnualReport/AnnualReportAccessService.cs
- EPlast/EPlast.Tests/Services/AnnualReport/AnnualReportAccessServiceTests.cs
> Fixed access for editing city annual report

- EPlast/EPlast.BLL/Interfaces/GoverningBodies/Sector/ISectorService.cs
- EPlast/EPlast.BLL/Services/GoverningBodies/Sector/SectorService.cs
- EPlast/EPlast.Tests/Controllers/GoverningBodySectorsControllerTests.cs
- EPlast/EPlast.Tests/Services/GoverningBody/Sector/SectorServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/GoverningBodySectorsController.cs
- EPlast/EPlast.WebApi/Mapping/GoverningBody/Sector/SectorTableProfile.cs
- EPlast/EPlast.WebApi/Models/GoverningBody/Sector/SectorTableViewModel.cs
- EPlast/EPlast.WebApi/StartupExtensions/AddRecurringJobManager.cs
> Updated SectorService, added recurring job

- EPlast/EPlast.BLL/Services/AnnualReport/AnnualReportAccessService.cs
> Added missing status check

- EPlast/EPlast.BLL/Services/AnnualReport/AnnualReportAccessService.cs
- EPlast/EPlast.Tests/Services/AnnualReport/AnnualReportAccessServiceTests.cs
> Access typo fix

- EPlast/EPlast.BLL/Services/EducatorsStaff/EducatorsStaffService.cs
- EPlast/EPlast.Tests/Services/EducatorStaff/EducatorsStaffServiceTests.cs
> check if role is restricted (Supporter) on creating kadra

- EPlast/EPlast.Resources/AuthenticationErrors.en.resx
- EPlast/EPlast.Tests/Controllers/AuthControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/AuthController.cs
> Add message when existing user registering

- EPlast/EPlast.BLL/Services/UserProfiles/UserProfileAccessService.cs
- EPlast/EPlast.Tests/Services/UserProfiles/UserProfileAccessServiceTests.cs
> Admins can approve only members of their city/region/hovel now(Fixed bug #2193)

- EPlast/EPlast.BLL/Interfaces/GoverningBodies/Announcement/IGoverningBodyAnnouncementService.cs
- EPlast/EPlast.BLL/Services/GoverningBodies/Announcement/GoverningBodyAnnouncementService.cs
- EPlast/EPlast.Tests/Controllers/GoverningBodiesControllerTests.cs
- EPlast/EPlast.Tests/Services/GoverningBody/Announcement/GoverningBodyAnnouncementServiceTest.cs
- EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
- EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> Announcement is now added to announcements without refreshing the page

- EPlast/EPlast.WebApi/Controllers/AnnualReportController.cs
> Fixed access to city annual report, role - head of okruga

- EPlast/EPlast.BLL/Handlers/CityHandlers/GetCityIdByUserIdHandler.cs
- EPlast/EPlast.BLL/Interfaces/City/ICityService.cs
- EPlast/EPlast.BLL/Queries/City/GetCityIdByUserIdQuery.cs
- EPlast/EPlast.BLL/Services/City/CityService.cs
- EPlast/EPlast.Tests/Handlers/City/GetCityIdByUserIdHendlerTest.cs
> Added mediator for GetCityIdByUserIdAsync method

- EPlast/EPlast.BLL/Interfaces/Terms/ITermsService.cs
- EPlast/EPlast.BLL/Services/TermsOfUse/TermsService.cs
- EPlast/EPlast.Tests/Controllers/TermsControllerTest.cs
- EPlast/EPlast.Tests/Services/Terms/TermsServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/TermsController.cs
> Notification sending to all but not to sender

- EPlast/EPlast.BLL/Commands/TermsOfUse/AddTermsCommand.cs
- EPlast/EPlast.BLL/Commands/TermsOfUse/ChangeTermsCommand.cs
- EPlast/EPlast.BLL/Handlers/TermsOfUse/AddTermsHandler.cs
- EPlast/EPlast.BLL/Handlers/TermsOfUse/ChangeTermsHandler.cs
- EPlast/EPlast.BLL/Handlers/TermsOfUse/CheckIfAdminForTermsHandler.cs
- EPlast/EPlast.BLL/Handlers/TermsOfUse/GetAllUsersIdWithoutSenderHandler.cs
- EPlast/EPlast.BLL/Handlers/TermsOfUse/GetFirstRecordTermsHandler.cs
- EPlast/EPlast.BLL/Queries/TermsOfUse/CheckIfAdminForTermsQuery.cs
- EPlast/EPlast.BLL/Queries/TermsOfUse/GetAllUsersIdWithoutSenderQuery.cs
- EPlast/EPlast.BLL/Queries/TermsOfUse/GetFirstRecordQuery.cs
- EPlast/EPlast.Tests/Handlers/Terms/AddTermsHandlerTest.cs
- EPlast/EPlast.Tests/Handlers/Terms/ChangeTermsHandlerTest.cs
- EPlast/EPlast.Tests/Handlers/Terms/CheckIfAdminForTermsHandlerTest.cs
- EPlast/EPlast.Tests/Handlers/Terms/GetAllUsersIdWithoutSenderHandlerTest.cs
- EPlast/EPlast.Tests/Handlers/Terms/GetFirstRecordHandlerTest.cs
> Added mediator for Terms service

- EPlast/EPlast.BLL/Interfaces/Region/IRegionAnnualReportService.cs
- EPlast/EPlast.BLL/Services/AnnualReport/AnnualReportService.cs
- EPlast/EPlast.BLL/Services/Region/RegionAnnualReportService.cs
- EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
- EPlast/EPlast.Tests/Services/Regions/RegionAnnualReportServiceTest.cs
- EPlast/EPlast.WebApi/Controllers/RegionsController.cs
- EPlast/EPlast.XUnitTest/Services/AnnualReport/AnnualReportServiceTests.cs
> Fixed accesses to annual report due to URL

- EPlast/EPlast.BLL/DTO/Admin/FilterTableParametersByRole.cs
- EPlast/EPlast.BLL/Interfaces/Admin/IAdminService.cs
- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
- EPlast/EPlast.DataAccess/Repositories/Interfaces/Admin/IAdminTypeRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Admin/AdminTypeRepository.cs
- EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
- EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/AdminController.cs
> UserTable access by roles

- EPlast/EPlast.BLL/DTO/EducatorsStaff/EducatorsStaffTableSettingsDTO.cs
- EPlast/EPlast.BLL/Interfaces/EducatorsStaff/IEducatorsStaffService.cs
- EPlast/EPlast.BLL/Mapping/EducatorsStaff/EducatorsStaffProfile.cs
- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
- EPlast/EPlast.BLL/Services/EducatorsStaff/EducatorsStaffService.cs
- EPlast/EPlast.Tests/Controllers/EducatorsStaffControllerTests.cs
- EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
- EPlast/EPlast.Tests/Services/EducatorStaff/EducatorsStaffServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/EducatorsStaffController.cs
- EPlast/EPlast.WebApi/appsettings.json
> Fix tables

- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
- EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
> improve city condition access

- EPlast/EPlast.BLL/DTO/EventUser/EventCreationDTO.cs
- EPlast/EPlast.BLL/Services/EventUser/EventUserManager.cs
- EPlast/EPlast.Tests/Controllers/EventsUsersControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/EventsUsersController.cs
- EPlast/EPlast.XUnitTest/Services/Events/EventUserManagerTests.cs
> Added test, rewrited controller, service

- EPlast/EPlast.BLL/DTO/AnnualReport/AnnualReportDTO.cs
- EPlast/EPlast.DataAccess/Entities/AnnualReport/AnnualReport.cs
> Changed type of mooney in creating city annual repport

- EPlast/EPlast.BLL/DTO/EventUser/EventCreationDTO.cs
- EPlast/EPlast.DataAccess/Entities/Event/Event.cs
- EPlast/EPlast.DataAccess/Migrations/20220315103905_questionFieldNoMoreRequiredInActionForm.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20220315103905_questionFieldNoMoreRequiredInActionForm.cs
> Questions no more required in event form #2147

- EPlast/EPlast.Resources/Roles.cs
> Updated Roles - GoverningBodyAdmin has the same access levels as SuperAdmin.

- EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/UserController.cs
> Updated GoverningBodyAdmin access levels at Profile

- EPlast/EPlast.BLL/Services/City/CityAccess/CityAccessService.cs
- EPlast/EPlast.BLL/Settings/CityAccessSettings.cs
- EPlast/EPlast.BLL/Settings/ClubAccessSettings.cs
- EPlast/EPlast.BLL/Settings/RegionAccessSettings.cs
> Updated GoverningBodyAdmin access levels at AnnualReports

- EPlast/EPlast.BLL/Services/Distinctions/UserDistinctionService.cs
- EPlast/EPlast.Resources/Roles.cs
- EPlast/EPlast.WebApi/Controllers/DistinctionController.cs
> Updated GoverningBodyAdmin access levels at Distinctions

- EPlast/EPlast.BLL/EPlast.BLL.csproj
- EPlast/EPlast.BLL/Interfaces/GoverningBodies/Announcement/IHtmlService.cs
- EPlast/EPlast.BLL/Services/GoverningBodies/Announcement/GoverningBodyAnnouncementService.cs
- EPlast/EPlast.BLL/Services/GoverningBodies/Announcement/HtmlService.cs
- EPlast/EPlast.BLL/Services/GoverningBodies/Sector/SectorAnnouncementsService.cs
- EPlast/EPlast.Tests/Controllers/GoverningBodiesControllerTests.cs
- EPlast/EPlast.Tests/Controllers/GoverningBodySectorsControllerTests.cs
- EPlast/EPlast.Tests/Services/GoverningBody/Announcement/GoverningBodyAnnouncementServiceTest.cs
- EPlast/EPlast.Tests/Services/GoverningBody/Announcement/HtmlServiceTests.cs
- EPlast/EPlast.Tests/Services/GoverningBody/Sector/SectorAnnouncementsServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/GoverningBodiesController.cs
- EPlast/EPlast.WebApi/Controllers/GoverningBodySectorsController.cs
- EPlast/EPlast.WebApi/StartupExtensions/AddDependenciesExtension.cs
> Empty announcements fix

- EPlast/EPlast.WebApi/Controllers/EventsController.cs
> Wrong user cannot reject other user

- EPlast/EPlast.WebApi/AccessSecurityModel/MenuAccessSettings.json
> Menu item is visible in menu for a Registered User #2420

- EPlast/EPlast.BLL/Services/Club/ClubParticipantsService.cs
> change contiditon for add head without enddate

- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
Виправив що станиця створюється архівованою, коли її створює княгиня або крайовий
> Fix City created as archived by Admin and GBAdmin

- EPlast/EPlast.BLL/Services/Statistics/StatisticsService.cs
> Only return Approved Reports

- EPlast/EPlast.WebApi/AccessSecurityModel/MenuAccessSettings.json
- EPlast/EPlast.WebApi/Controllers/MethodicDocumentsController.cs
> Security fixed

- EPlast/EPlast.BLL/Services/Events/ActionManager.cs
- EPlast/EPlast.Tests/Services/Events/ActionManagerTests.cs
- EPlast/EPlast.WebApi/StartupExtensions/AddRecurringJobManager.cs
- EPlast/EPlast.XUnitTest/Services/Events/ActionManagerTests.cs
> Event ends more often and user receives notification properly #2121 and #2411

- EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
- EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
- EPlast/EPlast.Tests/Services/City/CityParticipantsServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/AdminController.cs
Complements the first PR (#2430) , eliminates all warnings of compiler
> Fix obsolete warnings

- EPlast/EPlast.BLL/Handlers/CityHandlers/GetCityByIdWthFullInfoHandler.cs
> Fix trouble with member deleting

- EPlast/EPlast.BLL/Interfaces/EducatorsStaff/IEducatorsStaffService.cs
- EPlast/EPlast.BLL/Services/EducatorsStaff/EducatorsStaffService.cs
- EPlast/EPlast.DataAccess/Repositories/Interfaces/EducatorsStaff/IEducatorsStaffRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Interfaces/User/IUserDistinctionRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Interfaces/User/IUserPrecautionRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Decision/DecesionRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/EducatorsStaff/EducatorsStaffRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/MethodicDocument/MethodicDocumentRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/User/UserDistinctionRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/User/UserPrecautionRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/User/UserRenewalRepository.cs
- EPlast/EPlast.Tests/Services/EducatorStaff/EducatorsStaffServiceTests.cs
Removed procedures: 
- GetKadras
- getMethodicDocuments
- getDecisionsInfo
- getDistinctionsInfo
- usp_GetUserRenewals 
- getPrecautionsInfo
ToDo
Removed procedures: 
- GetKadras
- getMethodicDocuments
- getDecisionsInfo
- getDistinctionsInfo
- usp_GetUserRenewals 
- getPrecautionsInfo
ToDo
> Stored procedures removal

- EPlast/EPlast.BLL/Handlers/RegionHandlers/GetAllRegionsByPageAndIsArchiveHandler.cs
> Hide "Крайовий Провід Пласту" from Regions

- EPlast/EPlast.DataAccess/Entities/UserEntities/UserTableObject.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Admin/AdminTypeRepository.cs
> Added tab sorting at UserTable

- EPlast/EPlast.BLL/Services/Region/RegionAdministrationService.cs
Fix issue https://github.com/ita-social-projects/EPlast/issues/2012
dev
ToDo
ToDo
ToDo
> Fix issue #2012

- EPlast/EPlast.Tests/Controllers/AuthControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/AuthController.cs
- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
> Fixup 2 for Refactor AuthController

- EPlast/EPlast.BLL/DTO/UserAuthentication/RegisterDto.cs
- EPlast/EPlast.BLL/Mapping/User/Registration_User.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserProfile.cs
- EPlast/EPlast.DataAccess/ExtensionMethods/ModelBuilderExtensions.cs
- EPlast/EPlast.DataAccess/Migrations/20220629085151_Fixup2578.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20220629085151_Fixup2578.cs
> FIxup 4 for #2578

- EPlast/EPlast.BLL/Handlers/CityHandlers/GetCityByIdWthFullInfoHandler.cs
> Fix for link in City provid

- EPlast/EPlast.BLL/Interfaces/Region/IRegionService.cs
- EPlast/EPlast.BLL/Services/Region/RegionService.cs
- EPlast/EPlast.Tests/Controllers/AdminControllerTests.cs
- EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
- EPlast/EPlast.Tests/Services/Regions/RegionServiceTest.cs
- EPlast/EPlast.WebApi/Controllers/AdminController.cs
- EPlast/EPlast.WebApi/Controllers/RegionsController.cs
> Modify CreateFollower logic and add Get SuperAdmins endpoint for notifications

- EPlast/EPlast.DataAccess/Entities/Region/RegionFollowers.cs
- EPlast/EPlast.DataAccess/Migrations/20220701065839_AddOblastToRegionFollower.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20220701065839_AddOblastToRegionFollower.cs
> Add Oblast field to RegionFollower model

- EPlast/EPlast.DataAccess/Migrations/20220701065839_AddOblastToRegionFollower.cs
> Fix RegionFollower migration

- EPlast/EPlast.WebApi/Controllers/CourseController.cs
> fix action in courseController

- EPlast/EPlast.DataAccess/Repositories/Realizations/City/CityRepository.cs
- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
Closes https://github.com/ita-social-projects/EPlast/issues/2645
> Fix switcher

- EPlast/EPlast.BLL/Services/Region/RegionService.cs
> Change Oblast in Region Fix

- EPlast/EPlast.BLL/DTO/UserProfiles/UserTableDTO.cs
- EPlast/EPlast.BLL/Interfaces/City/ICityParticipantsService.cs
- EPlast/EPlast.BLL/Interfaces/EmailSending/IEmailContentService.cs
- EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
- EPlast/EPlast.BLL/Services/EmailSending/EmailContentService.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserTableObject.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Admin/AdminTypeRepository.cs
- EPlast/EPlast.Tests/Controllers/CityControllerTests.cs
- EPlast/EPlast.Tests/Services/City/CityParticipantsServiceTests.cs
- EPlast/EPlast.Tests/Services/EmailSending/EmailContentServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
> Add comment for RemoveFollower option and UT filter for followers

- EPlast/EPlast.BLL/DTO/UserProfiles/UserTableDTO.cs
- EPlast/EPlast.BLL/Interfaces/City/ICityParticipantsService.cs
- EPlast/EPlast.BLL/Interfaces/EmailSending/IEmailContentService.cs
- EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
- EPlast/EPlast.BLL/Services/EmailSending/EmailContentService.cs
- EPlast/EPlast.BLL/Services/Region/RegionService.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserTableObject.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Admin/AdminTypeRepository.cs
- EPlast/EPlast.Tests/Controllers/CityControllerTests.cs
- EPlast/EPlast.Tests/Services/City/CityParticipantsServiceTests.cs
- EPlast/EPlast.Tests/Services/EmailSending/EmailContentServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
> Merge to production

- EPlast/EPlast.Tests/Controllers/AuthControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/AuthController.cs
This reverts https://github.com/ita-social-projects/EPlast/pull/2678
> Revert fix registration error

- EPlast/EPlast.BLL/Services/ActiveMembership/AccessLevelService.cs
- EPlast/EPlast.BLL/Services/ActiveMembership/PlastDegreeService.cs
- EPlast/EPlast.Tests/Services/ActiveMembership/AccessLevelServiceTests.cs
- EPlast/EPlast.Tests/Services/ActiveMembership/PlastDegreeServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/ActiveMembershipController.cs
> Fix duplicating Supporter role when assigning a "Пластрият" degree

- EPlast/EPlast.BLL/DTO/UserAuthentication/RegisterDto.cs
- EPlast/EPlast.BLL/Interfaces/City/ICityParticipantsService.cs
- EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
- EPlast/EPlast.BLL/Services/EmailSending/EmailContentService.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/User.cs
- EPlast/EPlast.DataAccess/Migrations/20220727100608_AddCityIdToUser.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20220727100608_AddCityIdToUser.cs
- EPlast/EPlast.Tests/Controllers/AuthControllerTests.cs
- EPlast/EPlast.Tests/Services/EmailSending/EmailContentServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/AuthController.cs
- EPlast/EPlast.WebApi/Startup.cs
^ зробив це як для станиць, так і для округ (коли юзер не обрав станицю при реєстрації)
Також тепер всі повідомлення приходять лише після підтвердження пошти юзером, а не до цього.
> Email link

- EPlast/EPlast.WebApi/AccessSecurityModel/UserProfileAccessSettings.json
> Add Blanks access to Follower

- EPlast/EPlast.BLL/DTO/Decision/DecisionTargetDTO.cs
- EPlast/EPlast.Tests/Controllers/DecisionsControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/DecisionsController.cs
> Fix 2686 attempt 2

- EPlast/EPlast.BLL/DTO/UserProfiles/UserDTO.cs
- EPlast/EPlast.BLL/Services/UserProfiles/UserProfileAccessService.cs
- EPlast/EPlast.BLL/Services/UserProfiles/UserService.cs
- EPlast/EPlast.Tests/Controllers/UserControllerTests.cs
- EPlast/EPlast.Tests/Services/UserProfiles/UserProfileAccessServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/UserController.cs
> Full user profile access fix

- EPlast/EPlast.DataAccess/Repositories/Realizations/Admin/AdminTypeRepository.cs
closes https://github.com/ita-social-projects/EPlast/issues/2740
dev
ToDo
ToDo
ToDo
> #2740-back-sorting

- EPlast/EPlast.WebApi/AccessSecurityModel/CityAccessSettings.json
Closes https://github.com/ita-social-projects/EPlast/issues/2756
But this problem was not with Region Admin. It was with Governing Body Admin
ToDo
ToDo
ToDo
> Now GoverningBody Admin can't archive a city

- EPlast/EPlast.BLL/Services/UserAccess/UserAccessService.cs
- EPlast/EPlast.BLL/Services/UserProfiles/UserProfileAccessService.cs
- EPlast/EPlast.DataAccess/ExtensionMethods/ModelBuilderExtensions.cs
- EPlast/EPlast.DataAccess/Migrations/20220831120941_CourseSeeding.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20220831120941_CourseSeeding.cs
Closes https://github.com/ita-social-projects/EPlast/issues/2701
ToDo
ToDo
ToDo
> Now user can watch, download and delete himself certificates

- EPlast/EPlast.BLL/Interfaces/Blank/IBlankAchievementDocumentService.cs
- EPlast/EPlast.BLL/Services/Blank/AchievementDocumentService.cs
- EPlast/EPlast.Tests/Controllers/BlanksControllerTests.cs
- EPlast/EPlast.Tests/Services/Blank/BlankAchievementsServiceTest.cs
- EPlast/EPlast.WebApi/Controllers/BlanksController.cs
> Achievements filtration by courses

- EPlast/EPlast.BLL/Handlers/CityHandlers/GetCityByIdHandler.cs
Coupled with https://github.com/ita-social-projects/EPlast-Client/pull/1059
ToDo
ToDo
ToDo
> #2510 Fix Renewal notification

- azure-pipelines.yml
> check kubectl version

- azure-pipelines.yml
> add messages

- azure-pipelines.yml
> test get creds command

- azure-pipelines.yml
> create kubernetes secret to test kube connection

- azure-pipelines.yml
> test the new dockerRegistryServiceConnection value

- manifests/test/cert-issuer-prod.yml
- manifests/test/cert-prod.yml
- manifests/test/deployment.yml
- manifests/test/ingress-prod.yml
- manifests/test/redis-master-deployment.yaml
> update manifests' version and syntax

- manifests/test/deployment.yml
- manifests/test/redis-master-deployment.yaml
> change version of autoscaling/v2 to version autoscaling/v1

- manifests/test/deployment.yml
- manifests/test/redis-master-deployment.yaml
> updated HorizontalPodAutoscaler syntax to the new version syntax

- manifests/test/ingress-prod.yml
> update ingress api version

- azure-pipelines.yml
> remove unused lines of code

- EPlast/EPlast.Tests/Controllers/RegionsControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/CitiesController.cs
- EPlast/EPlast.WebApi/Controllers/RegionsController.cs
Coupled with https://github.com/ita-social-projects/EPlast-Client/pull/1079
> #2764_Fix_City_Application_Access

- azure-pipelines-prod.yml
- manifests/prod/deployment.yml
- manifests/prod/ingress-argocd.yml
- manifests/prod/ingress-monitoring.yml
- manifests/prod/ingress-prod.yml
- manifests/test/deployment.yml
> update manifest files & update syntax azure-pipelines

- manifests/prod/deployment.yml
- manifests/prod/ingress-argocd.yml
- manifests/prod/ingress-monitoring.yml
- manifests/prod/ingress-prod.yml
- manifests/test/deployment.yml
> update manifest files syntax

- EPlast/EPlast.Tests/Controllers/AuthControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/AuthController.cs
- EPlast/EPlast.WebApi/Startup.cs
- Reverted changes to enable email verification
- Added URL encoding to token for email verification
> Email verification fix

- Dockerfile
- EPlast/EPlast.WebApi/Properties/launchSettings.json
> modify definding var

- Dockerfile
- EPlast/EPlast.WebApi/Properties/launchSettings.json
- azure-pipelines-prod.yml
> Test var usage

- Dockerfile
- EPlast/EPlast.WebApi/Properties/launchSettings.json
> define vars with yaml syntax

- Dockerfile
- EPlast/EPlast.WebApi/Properties/launchSettings.json
- azure-pipelines-prod.yml
- azure-pipelines.yml
> put changes back

- Dockerfile
- EPlast/EPlast.WebApi/Properties/launchSettings.json
- azure-pipelines-prod.yml
- azure-pipelines.yml
> add arguments

- EPlast/EPlast.Tests/Controllers/ClubControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/ClubController.cs
I added new controller for clubs to get clubs administration. It helped me to fix the bug
Closes: https://github.com/ita-social-projects/EPlast/issues/2705
Coupled with: https://github.com/ita-social-projects/EPlast-Client/pull/1135/
ToDo
ToDo
ToDo
> Fix notifications aren't sent to user after removing/adding its role from User Table

- EPlast/EPlast.DataAccess/Repositories/Realizations/AnnualReport/AnnualReportsRepository.cs
- EPlast/EPlast.WebApi/Properties/launchSettings.json
- EPlast/EPlast.WebApi/StartupExtensions.cs
#closes https://github.com/ita-social-projects/EPlast/issues/2862
#closes https://github.com/ita-social-projects/EPlast/issues/2860
dev
ToDo
ToDo
ToDo
> Fix-Renewal-2860-2862

- EPlast/EPlast.BLL/DTO/UserProfiles/UserTableDTO.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserTableObject.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Admin/AdminTypeRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Region/RegionAnnualReportRepository.cs
> addFullName

- EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
- EPlast/EPlast.Tests/Services/City/CityParticipantsServiceTests.cs
closes https://github.com/ita-social-projects/EPlast/issues/1897
> Fix-#1897. Region administration role loss on changing city from different region

- EPlast/EPlast.BLL/DTO/ActiveMembership/UserMembershipDatesDTO.cs
- EPlast/EPlast.BLL/DTO/UserProfiles/UserTableDTO.cs
- EPlast/EPlast.BLL/Interfaces/UserProfiles/IUserRenewalService.cs
- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
- EPlast/EPlast.BLL/Services/UserProfiles/UserRenewalService.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserMembershipDates.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserTableObject.cs
- EPlast/EPlast.DataAccess/Migrations/20221030121217_MembershipDate.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20221030121217_MembershipDate.cs
- EPlast/EPlast.DataAccess/Repositories/Interfaces/User/IUserRenewalRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Admin/AdminTypeRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/User/UserRenewalRepository.cs
- EPlast/EPlast.Tests/Controllers/LoginControllerTests.cs
- EPlast/EPlast.Tests/Controllers/UserRenewalControllerTests.cs
- EPlast/EPlast.Tests/Services/UserProfiles/UserRenewalServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/UserRenewalController.cs
> userTableChanges

- EPlast/EPlast.BLL/Interfaces/ActiveMembership/IUserDatesService.cs
- EPlast/EPlast.BLL/Services/ActiveMembership/UserDatesService.cs
- EPlast/EPlast.BLL/Services/FormerMember/FormerMemberService.cs
- EPlast/EPlast.BLL/Services/UserProfiles/UserRenewalService.cs
- EPlast/EPlast.DataAccess/EPlastDBContext.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/User.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserFormerMembershipDates.cs
- EPlast/EPlast.DataAccess/Entities/UserEntities/UserFormerMembershipTable.cs
- EPlast/EPlast.DataAccess/Migrations/20221031153311_PreviousTable.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20221031153311_PreviousTable.cs
- EPlast/EPlast.DataAccess/Repositories/Interfaces/Base/IRepositoryWrapper.cs
- EPlast/EPlast.DataAccess/Repositories/Interfaces/User/IUserFormerMembershipDatesRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Base/RepositoryWrapper.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/User/UserFormerMembershipDatesRepository.cs
- EPlast/EPlast.Tests/Controllers/ActiveMembershipControllerTests.cs
- EPlast/EPlast.Tests/Services/UserProfiles/UserRenewalServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/ActiveMembershipController.cs
> addFormerDatesTable

- EPlast/EPlast.Tests/Controllers/EventsControllerTests.cs
- EPlast/EPlast.WebApi/Controllers/EventsController.cs
> EventControllerTests refactoring

- EPlast/EPlast.Tests/Controllers/EventsControllerTests.cs
> Remove warning comment

- EPlast/EPlast.DataAccess/Repositories/Realizations/MethodicDocument/MethodicDocumentRepository.cs
closes https://github.com/ita-social-projects/EPlast/issues/2950
> Fix-#2950. Fixed search by date on [Legislation/Репозитарій] page

- EPlast/EPlast.BLL/Services/Events/ActionManager.cs
closes https://github.com/ita-social-projects/EPlast/issues/2944
> Fix-#2944. Removed notification sending for the user who did not participate in event

- EPlast/EPlast.BLL/DTO/Admin/TableFilterParameters.cs
- EPlast/EPlast.BLL/Services/Admin/AdminService.cs
- EPlast/EPlast.DataAccess/Repositories/Interfaces/Admin/IAdminTypeRepository.cs
- EPlast/EPlast.DataAccess/Repositories/Realizations/Admin/AdminTypeRepository.cs
- EPlast/EPlast.Tests/Services/Admin/AdminServiceTests.cs
> kadraFilterApi

- EPlast/EPlast.WebApi/Controllers/UserController.cs
- EPlast/EPlast.WebApi/Models/UserModels/PersonalDataViewModel.cs
- EPlast/EPlast.WebApi/Models/UserModels/UserApproversViewModel.cs
> checkForTimer

- EPlast/EPlast.BLL/Interfaces/Precautions/IUserPrecautionService.cs
- EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
- EPlast/EPlast.Tests/Controllers/PrecautionControllerTests.cs
- EPlast/EPlast.Tests/Services/Precautions/UserPrecautionServiceTests.cs
- EPlast/EPlast.WebApi/Controllers/PrecautionController.cs
closes https://github.com/ita-social-projects/EPlast/issues/2917
> Fix #2917. Made restrictions for adding precautions under the existing number

- EPlast/EPlast.Tests/Controllers/CourseControllerTest.cs
- EPlast/EPlast.XUnitTest/Services/Azure/AzureBlobConnectionFactoryTests.cs
- EPlast/EPlast.XUnitTest/Services/Educators/EducatorsStaffTypesServiceTests.cs
- EPlast/EPlast.XUnitTest/Services/Events/ActionManagerTests.cs
- EPlast/EPlast.XUnitTest/Services/TextFormatting/TextFormatterTests.cs
> New x unit tests

- EPlast/EPlast.BLL/Services/GoverningBodies/GoverningBodyAdministrationService.cs
- EPlast/EPlast.BLL/Services/GoverningBodies/Sector/SectorAdministrationService.cs
- EPlast/EPlast.WebApi/Controllers/LoginController.cs
> Fixed own code smells

- EPlast/EPlast.BLL/Handlers/PrecautionHandlers/GetUsersPrecautionsForTableHandler.cs
- EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
closes https://github.com/ita-social-projects/EPlast/issues/2916
> Fix-#2916. Implemented search by status in Precaution table

- EPlast/EPlast.BLL/Services/City/CityParticipantsService.cs
closes https://github.com/ita-social-projects/EPlast/issues/2758
> Fix-#2758. User's city did not match his current region fix

- EPlast/EPlast.BLL/Services/Precautions/UserPrecautionService.cs
- EPlast/EPlast.Tests/Services/Precautions/UserPrecautionServiceTests.cs
- EPlast/EPlast.WebApi/AccessSecurityModel/PrecautionsAccessSettings.json
> Precautions addition accesses modification for GB admin

- EPlast/EPlast.XUnitTest/Services/AzureStorage/Base/BlobStorageRepositoryTests.cs
- EPlast/EPlast.XUnitTest/Services/Blank/CourseServiceTests.cs
- EPlast/EPlast.XUnitTest/Services/Blank/UserCourseServiceTests.cs
- EPlast/EPlast.XUnitTest/Services/HostURL/HostURLServiceTests.cs
- EPlast/EPlast.XUnitTest/Services/Logging/LoggerServiceTests.cs
> X unit tests tatiana

- EPlast/EPlast.WebApi/AccessSecurityModel/EventUserAccessSettings.json
- EPlast/EPlast.WebApi/Controllers/EventsController.cs
Closes: https://github.com/ita-social-projects/EPlast/issues/2936
Coupled with: https://github.com/ita-social-projects/EPlast/pull/2960
ToDo
ToDo
ToDo
> Added restrictions for editing event categories

- EPlast/EPlast.BLL/Handlers/PrecautionHandlers/GetUsersPrecautionsForTableHandler.cs
- EPlast/EPlast.DataAccess/ExtensionMethods/ModelBuilderExtensions.cs
- EPlast/EPlast.DataAccess/Migrations/20221129121038_RenamedPrecautions.Designer.cs
- EPlast/EPlast.DataAccess/Migrations/20221129121038_RenamedPrecautions.cs
Renamed precautions to "І Пересторога, "ІІ Пересторога", "ІІІ Пересторога".
> Renaming precautions improvement
